import Link from "next/link"

export const metadata = {
  title: "Disclaimer | Docket One",
  description: "Docket One legal disclaimer regarding the use of our calculators and accuracy of results.",
}

export default function DisclaimerPage() {
  return (
    <div className="almanac"><div className="almanac-page">
      <div className="almanac-top"><Link className="almanac-back" href="/">← home</Link><span>Docket One</span></div>
      <header className="almanac-masthead">
        <div className="almanac-eyebrow">Legal</div>
        <h1 className="almanac-h1 sm">Disclaimer</h1>
        <p className="almanac-sub">Important: Please read this disclaimer carefully before using any calculators on Docket One.</p>
      </header>
      <div className="almanac-prose">
        <p>Effective Date: December 20, 2024</p>

        <h2>No Professional Advice</h2>
        <p>
          The information and results provided by the calculators on Docket One (docket.one) are for <strong>educational and informational purposes only</strong>. They do not constitute professional advice, whether financial, legal, medical, or otherwise.
        </p>
        <p>
          You should not rely on the results generated by these tools for making real-world decisions. Always consult with a qualified professional before taking any action based on calculations provided by this website.
        </p>

        <h2>Accuracy of Information</h2>
        <p>
          While we strive to ensure that our calculator logic is based on current data and standard mathematical models, we make no guarantees regarding the accuracy, reliability, or completeness of the results.
        </p>
        <p>
          Many of our calculators (especially those in the &quot;Geek Galaxy&quot; or &quot;Otaku Ops&quot; categories) are based on fictional scenarios or stylized models and should be treated as entertainment.
        </p>

        <h2>Assumption of Risk</h2>
        <p>
          By using Docket One, you acknowledge that any reliance on the information provided is at your own risk. Docket One and its operators shall not be held liable for any loss, damage, or injury resulting from the use or misuse of our tools.
        </p>

        <h2>External Links</h2>
        <p>
          Our website may contain links to third-party websites. We are not responsible for the content, privacy policies, or practices of any third-party sites.
        </p>

        <h2>Contact Us</h2>
        <p>
          If you have any questions regarding this disclaimer, please contact us at:
        </p>
        <p>
          <a href="mailto:legal@docket.one">legal@docket.one</a>
        </p>
      </div>
      <div className="almanac-foot"><span>© 2026 Docket One</span><Link href="/">Home →</Link></div>
    </div></div>
  )
}
