import { TypographyH1, TypographyH2, TypographyP } from "@/components/ui/typography"

export const metadata = {
  title: "Disclaimer | Docket One",
  description: "Docket One legal disclaimer regarding the use of our calculators and accuracy of results.",
}

export default function DisclaimerPage() {
  return (
    <main className="flex-1 bg-background relative selection:bg-primary/30">
        <div className="fixed inset-0 -z-10 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-indigo-500/5 via-background to-background" />

        <div className="container py-16 md:py-24 max-w-4xl mx-auto">
            <header className="mb-12 text-center text-muted-foreground">
                <TypographyH1 className="text-foreground text-gradient mb-4">Disclaimer</TypographyH1>
                <p>Effective Date: December 20, 2024</p>
                <TypographyP className="max-w-2xl mx-auto mt-4 text-rose-500 font-bold">
                    Important: Please read this disclaimer carefully before using any calculators on Docket One.
                </TypographyP>
            </header>

            <div className="space-y-12 prose prose-invert max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-a:text-primary">
                
                <section className="glass-card p-8 rounded-xl border-white/10 border-rose-500/20">
                    <TypographyH2>No Professional Advice</TypographyH2>
                    <TypographyP>
                        The information and results provided by the calculators on Docket One (docket.one) are for <strong>educational and informational purposes only</strong>. They do not constitute professional advice, whether financial, legal, medical, or otherwise.
                    </TypographyP>
                    <TypographyP>
                        You should not rely on the results generated by these tools for making real-world decisions. Always consult with a qualified professional before taking any action based on calculations provided by this website.
                    </TypographyP>
                </section>

                <section className="space-y-6">
                    <TypographyH2>Accuracy of Information</TypographyH2>
                    <TypographyP>
                        While we strive to ensure that our calculator logic is based on current data and standard mathematical models, we make no guarantees regarding the accuracy, reliability, or completeness of the results. 
                    </TypographyP>
                    <TypographyP>
                        Many of our calculators (especially those in the "Geek Galaxy" or "Otaku Ops" categories) are based on fictional scenarios or stylized models and should be treated as entertainment.
                    </TypographyP>
                </section>

                <section className="space-y-6">
                    <TypographyH2>Assumption of Risk</TypographyH2>
                    <TypographyP>
                        By using Docket One, you acknowledge that any reliance on the information provided is at your own risk. Docket One and its operators shall not be held liable for any loss, damage, or injury resulting from the use or misuse of our tools.
                    </TypographyP>
                </section>

                <section className="space-y-6">
                    <TypographyH2>External Links</TypographyH2>
                    <TypographyP>
                        Our website may contain links to third-party websites. We are not responsible for the content, privacy policies, or practices of any third-party sites.
                    </TypographyP>
                </section>

                <section className="space-y-6">
                    <TypographyH2>Contact Us</TypographyH2>
                    <TypographyP>
                        If you have any questions regarding this disclaimer, please contact us at:
                    </TypographyP>
                    <TypographyP>
                        <a href="mailto:legal@docket.one" className="text-primary hover:underline">legal@docket.one</a>
                    </TypographyP>
                </section>
            </div>
        </div>
    </main>
  )
}
